# Generated by Django 4.2.5 on 2023-10-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('evento', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
            ],
        ),
    ]
