# Generated by Django 4.2.5 on 2023-10-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='evento',
        ),
    ]
