# Generated by Django 4.2.5 on 2023-10-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_viaje_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='ciudad',
            field=models.CharField(max_length=40),
        ),
    ]
