# Generated by Django 4.2.5 on 2023-10-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_viaje_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='ciudad',
            field=models.CharField(max_length=50),
        ),
    ]
