# Generated by Django 4.2.5 on 2023-10-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevaapp', '0002_alter_tips_actividad_alter_tips_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tips',
            options={'verbose_name_plural': 'Tips'},
        ),
    ]
